# -*- coding: utf-8 -*-

SYNTAX_ERROR = 0
INT = 1
FLOAT = 2
DOUBLE = 3
STRING = 4;
OPENING_PARENTHESIS = 5
LIST = 5 # OPENING_PARENTHESIS and LIST have purposely the same value!
CLOSING_PARENTHESIS = 6
SYMBOL = 7
RATIO = 8
QUOTE = 9
BACKQUOTE = 10
COMMA_AT = 11
COMMA = 12
HASH = 13
EOF = 14

FUN_OBJ = 30
MACRO_OBJ = 31
